#!/usr/bin/env php
<?php

include __DIR__ . '/bootstrap.php';

$params = require __DIR__ . '/config/params.php';

if (file_exists(__DIR__ . '/config/params-local.php')) {
    $params = array_merge($params, require __DIR__ . '/config/params-local.php');
}

$application = new \yii\console\Application([
    'id' => 'sentry-tests',
    'basePath' => \Yii::getAlias('@tests'),
    'runtimePath' => \Yii::getAlias('@tests/_output'),
    'enableCoreCommands' => false,
    'controllerNamespace' => 'tests\commands',
    'bootstrap' => ['log'],
    'params' => $params,
    'components' => [
        'log' => [
            'targets' => [
                [
                    'class' => \yii\log\FileTarget::class
                ],
                [
                    'class' => \notamedia\sentry\SentryTarget::class,
                    'dsn' => $params['sentryDsn']
                ]
            ]
        ]
    ]
]);

$exitCode = $application->run();
exit($exitCode);
